name: snsinahub-valet/circleci/say-hello-workflow
on:
  push:
    branches:
    - main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v2
    - name: Say hello
      run: |
        echo Wowwww this one is triggered from GitHub! |
        echo top |
        env
